apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetrapgc
  namespace: security
  labels:
    app: tetrapgc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetrapgc
  template:
    metadata:
      labels:
        app: tetrapgc
    spec:
      serviceAccountName: tetrapgc-sa
      automountServiceAccountToken: false  # Prevents auto-mounting service account token

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: tetrapgc
          image: ghcr.io/abraxas618/tetrapgc:v1.2.3  # Use fixed version
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
          env:
            - name: QKD_SERVERS
              value: "qkd1.example.com,qkd2.example.com"  # Secure QKD Servers
            - name: QKD_PORT
              value: "5000"
            - name: DEVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: secure-storage
              mountPath: "/secure_storage"
              readOnly: false

      volumes:
        - name: secure-storage
          persistentVolumeClaim:
            claimName: tetrapgc-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: tetrapgc-service
  namespace: security
spec:
  selector:
    app: tetrapgc
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tetrapgc-pvc
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Defines persistent storage
