apiVersion: policy/v1
kind: PodSecurityPolicy
metadata:
  name: restricted-tetrapgc
spec:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: MustRunAs
  seccompProfile:
    type: RuntimeDefault