apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetrapgc
  labels:
    app: tetrapgc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetrapgc
  template:
    metadata:
      labels:
        app: tetrapgc
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: tetrapgc-container
        image: tetrapgc:latest
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
          - mountPath: /app/local
            name: pqc-libs
      volumes:
      - name: pqc-libs
        emptyDir: {}
