name: TetraCrypt CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # ✅ Updated to latest version

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install required dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

      # Run unit tests and security validation
    - name: Run Unit Tests
      run: |
        python run_tests.py

      # Run benchmarks to evaluate performance
    - name: Run Benchmarks
      run: |
        python tetracrypt.py benchmark > benchmark_results.txt

      # Upload benchmark results artifact (latest supported version)
    - name: Upload Benchmark Results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark_results
        path: benchmark_results.txt
